intf_libs = # Interface dependencies.
#import xxxx_libs += libhello%lib{hello}

./: lib{te} doc{README.md} manifest

lib{te}: {hxx ixx txx}{*} $intf_libs

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

# Export options.
#
lib{te}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

# Install recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
