name: Build & Run Tests On Various Configurations
on: [push]

jobs:

  build_run_tests:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        toolchain: [msvc, gcc, clang, clang16, gcc12]
        exclude:
          - os: ubuntu-latest
            toolchain: msvc
          - os: ubuntu-latest # TODO: Remove this one once the clang with libc++ is fixed
            toolchain: clang
          - os: ubuntu-latest
            toolchain: clang16
          - os: macos-latest
            toolchain: msvc
          - os: macos-latest # TODO: Remove this one once the clang of the system is fixed
            toolchain: gcc
          - os: macos-latest # TODO: Remove this one once the clang on macos is fixed
            toolchain: clang
          - os: windows-latest
            toolchain: gcc
          - os: windows-latest
            toolchain: gcc12

    name: Build & Run Tests
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        shell: bash
        run: ls -la "${{ github.workspace }}"

      # - name: Cache build2 install
      #   uses: actions/cache@v3
      #   with:
      #     path: ${{ BUILD2_BUILD_DIR }}
      #     key: build2-${{ runner.os }}-${{ hashFiles($BUILD2_BUILD_DIR/**) }}
      #     restore-keys: build2-${{ runner.os }}
      - name: Install build2
        uses: build2/setup-build2-github-action@v2
        with:
          build2-version: staged
      - name: build2 setup info
        shell: bash
        run: b --version && bdep --version && bpkg --version
      - run: echo "🍏 This job's status is ${{ job.status }}."

      - name: Install recent LLVM and Clang
        if: matrix.toolchain == 'clang'
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Install recent GCC
        if: startsWith('gcc', matrix.toolchain)
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Clang 16 version alias on non-linux OS
        if: matrix.toolchain == clang16 && not statsWith('ubuntu', matrix.os)
        run: sed -i -e "$aalias clang-16='clang'" ~/.bashrc && sed -i -e "$aalias clang++-16='clang++'" ~/.bashrc

      - name: GCC 12 version alias on non-linux OS
        if: matrix.toolchain == gcc12 && not statsWith('ubuntu', matrix.os)
        run: sed -i -e "$aalias gcc-12='gcc'" ~/.bashrc && sed -i -e "$aalias g++-12='g++'" ~/.bashrc

      - name: Info about clang
        if: startswith('clang', matrix.toolchain)
        run: clang++ --version

      - name: Info about gcc
        if: startsWith('gcc', matrix.toolchain)
        run: g++ --version

      # We omit trying to find `cl` from msvc because it's annoying, and the info is already in steps below.
      - name: Info about toolchain
        run: echo "Look into 'Create all build configurations' step for details about the toolchain."

      - name: "Install dependencies (Ubuntu only)"
        if: runner.os == 'Linux'
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y libx11-dev libxrandr-dev libudev-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev xorg-dev libvulkan-dev

      - name: Create all build configurations
        shell: bash
        run: ./init-configs.sh ${{ matrix.toolchain }}
      - name: Build All
        shell: bash
        run: bdep update -a
      - name: Run Tests
        shell: bash
        run: bdep test -a
      - name: Make sure it works with `b`
        shell: bash
        run: bdep clean -a && b "{update test}"
      - name: Install debug
        shell: bash
        run: "b install: build-${{ matrix.toolchain }}-debug/"
      - name: Install release
        shell: bash
        run: "b install: build-${{ matrix.toolchain }}-release/"


